name: Package Addon

on:
  push:
    branches: [ master ]
    tags: [ '*' ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install luarocks
        run: sudo apt-get install luarocks
      - name: Install luacheck
        run: luarocks install --local luacheck
      - name: Run luacheck
        run: ~/.luarocks/bin/luacheck . --no-color -q
  build:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create Packages
        uses: BigWigsMods/packager@master
        with:
          args: -S
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
